CREATE DATABASE AIRCRAFT;

CREATE TABLE EMPLOYEE (
	EMP_ID INT,
    EMP_LNAME TINYTEXT,
    PRIMARY KEY (EMP_ID)
    );
    
CREATE TABLE JOBS (
	JOB_NAME TINYTEXT,
    PRIMARY KEY (JOB_NAME)
    );
    
CREATE TABLE CUSTOMER (
	CUST_ID INT,
    CUST_LNAME TINYTEXT,
    PRIMARY KEY (CUST_ID)
    );

CREATE TABLE MODEL (
	MODEL_ID INT,
    MODEL_SEATS INT,
    MODEL_CHG_MILE INT,
    PRIMARY KEY (MODEL_ID)
    );
    
CREATE TABLE CHARTER_CUSTOMER (
	CHAR_ID INT,
    CUST_ID INT,
    PRIMARY KEY (CHAR_ID),
    PRIMARY KEY (CUST_ID)
    );

CREATE TABLE AIRCRAFT (
	AC_ID INT,
    MODEL_CODE INT,
    PRIMARY KEY (AC_ID),
    FOREIGN KEY (MODEL_ID) REFERENCES MODEL(MODEL_ID)
    );

CREATE TABLE CHARTER_EMPLOYEE (
	CHAR_TRIP INT,
    EMP_ID INT,
    JOB_ID INT,
    PRIMARY KEY (CHAR_ID),
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_NAME)
    );
    
CREATE TABLE CHARTER (
    CHAR_ID INT,
    CHAR_DATE DATE,
    CHAR_CITY TINYTEXT,
    CHAR_MILES DOUBLE,
    CHAR_PAX INT,
    CHAR_CARGO INT,
    CHAR_AC_ID INT,
    PRIMARY KEY (CHAR_ID),
    FOREIGN KEY (CHAR_AC_ID) REFERENCES AIRCRAFT(AC_ID)
    );
    
    